package Vista;

import Controlador.ControladorAgendarCita;
import Controlador.ControladorAgregarMascota;
import Controlador.ControladorHistorial;
import Controlador.ControladorMenuInicio;
import Controlador.ControladorModificarCliente;
import Controlador.ControladorRegistrarMascota;
import Controlador.ControladorVerMascotas;
import Excepciones.MascotaExcepcion;
import Modelo.VO.Cliente;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author danii
 */
public class VistaMenuInicio extends javax.swing.JDialog {

    /**
     * Creates new form Personal_1
     */
    public VistaMenuInicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public VistaMenuInicio() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlbMenuInicio = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();
        btn_agendar = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        lbl_mensaje = new javax.swing.JLabel();
        btn_cerrar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_mascotas = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 228, 228));
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(200, 228, 228));

        jlbMenuInicio.setFont(new java.awt.Font("The munday free version", 1, 24)); // NOI18N
        jlbMenuInicio.setForeground(new java.awt.Color(0, 102, 204));
        jlbMenuInicio.setText("MENU INICIO");
        jlbMenuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbMenuInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbMenuInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jlbMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jlbMenuInicio)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 102, 255));

        btn_salir.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(0, 102, 255));
        btn_salir.setText("Salir");
        btn_salir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_salir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_salirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_salirFocusLost(evt);
            }
        });
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_agendar.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_agendar.setForeground(new java.awt.Color(0, 102, 255));
        btn_agendar.setText("Agendar cita");
        btn_agendar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_agendar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_agendarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_agendarFocusLost(evt);
            }
        });
        btn_agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendarActionPerformed(evt);
            }
        });

        btn_ver.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_ver.setForeground(new java.awt.Color(0, 102, 255));
        btn_ver.setText("Ver citas");
        btn_ver.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_ver.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_verFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_verFocusLost(evt);
            }
        });
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        lbl_mensaje.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N

        btn_cerrar.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_cerrar.setForeground(new java.awt.Color(0, 102, 255));
        btn_cerrar.setText("Cerrar Sesion");
        btn_cerrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cerrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_cerrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_cerrarFocusLost(evt);
            }
        });
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        btn_modificar.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(0, 102, 255));
        btn_modificar.setText("Modificar Datos");
        btn_modificar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_modificar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_modificarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_modificarFocusLost(evt);
            }
        });
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modelo/Assets/Inicio.jpeg"))); // NOI18N

        btn_mascotas.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_mascotas.setForeground(new java.awt.Color(0, 102, 255));
        btn_mascotas.setText("Mis mascotas");
        btn_mascotas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_mascotas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_mascotasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_mascotasFocusLost(evt);
            }
        });
        btn_mascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mascotasActionPerformed(evt);
            }
        });

        btn_agregar.setFont(new java.awt.Font("The munday free version", 1, 14)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(0, 102, 255));
        btn_agregar.setText("Agregar mascota");
        btn_agregar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_agregar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_agregarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_agregarFocusLost(evt);
            }
        });
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(107, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_agendar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 24, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_agregar)
                                    .addComponent(btn_mascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agendar)
                    .addComponent(btn_mascotas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ver)
                    .addComponent(btn_agregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_salir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_cerrar)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendarActionPerformed
        // TODO add your handling code here:
        ControladorMenuInicio.agendarCita();
    }//GEN-LAST:event_btn_agendarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        ControladorMenuInicio.salir();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        // TODO add your handling code here:
        ControladorMenuInicio.verCitas();
    }//GEN-LAST:event_btn_verActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        // TODO add your handling code here:
        ControladorMenuInicio.cerrar();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_agendarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_agendarFocusGained
        // TODO add your handling code here:
        btn_agendar.setBackground(new Color(102, 204, 255));

    }//GEN-LAST:event_btn_agendarFocusGained

    private void btn_agendarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_agendarFocusLost
        // TODO add your handling code here:
        btn_agendar.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btn_agendarFocusLost

    private void btn_verFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_verFocusGained
        // TODO add your handling code here:
        btn_ver.setBackground(new Color(102, 204, 255));
    }//GEN-LAST:event_btn_verFocusGained

    private void btn_verFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_verFocusLost
        // TODO add your handling code here:
        btn_ver.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btn_verFocusLost

    private void btn_modificarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_modificarFocusGained
        // TODO add your handling code here:
        btn_modificar.setBackground(new Color(102, 204, 255));

    }//GEN-LAST:event_btn_modificarFocusGained

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        ControladorModificarCliente.mostrarVentana();
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_modificarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_modificarFocusLost
        // TODO add your handling code here:
        btn_modificar.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btn_modificarFocusLost

    private void btn_salirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_salirFocusGained
        // TODO add your handling code here:
        btn_salir.setBackground(new Color(102, 204, 255));
    }//GEN-LAST:event_btn_salirFocusGained

    private void btn_salirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_salirFocusLost
        // TODO add your handling code here:
        btn_salir.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btn_salirFocusLost

    private void btn_cerrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_cerrarFocusGained
        // TODO add your handling code here:
        btn_cerrar.setBackground(new Color(102, 204, 255));

    }//GEN-LAST:event_btn_cerrarFocusGained

    private void btn_cerrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_cerrarFocusLost
        // TODO add your handling code here
        btn_cerrar.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_btn_cerrarFocusLost

    private void btn_mascotasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_mascotasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mascotasFocusGained

    private void btn_mascotasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_mascotasFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mascotasFocusLost

    private void btn_mascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mascotasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            ControladorVerMascotas.mostrarVentana();
        } catch (MascotaExcepcion ex) {
            Logger.getLogger(VistaMenuInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_mascotasActionPerformed

    private void btn_agregarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_agregarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarFocusGained

    private void btn_agregarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_agregarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarFocusLost

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        ControladorAgregarMascota.mostrarVentana();
        this.setVisible(false);

    }//GEN-LAST:event_btn_agregarActionPerformed

    private void jlbMenuInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMenuInicioMouseEntered
        // TODO add your handling code here:
           jlbMenuInicio.setForeground(Color.PINK);
    }//GEN-LAST:event_jlbMenuInicioMouseEntered

    private void jlbMenuInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMenuInicioMouseExited
        // TODO add your handling code here:
        jlbMenuInicio.setForeground(new Color(0, 153, 204));
    }//GEN-LAST:event_jlbMenuInicioMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaMenuInicio dialog = new VistaMenuInicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JButton getBtn_agendar() {
        return btn_agendar;
    }

    public void setBtn_agendar(JButton btn_agendar) {
        this.btn_agendar = btn_agendar;
    }

    public JButton getBtn_ver() {
        return btn_ver;
    }

    public void setBtn_ver(JButton btn_ver) {
        this.btn_ver = btn_ver;
    }

    public JLabel getLbl_mensaje() {
        return lbl_mensaje;
    }

    public void setLbl_mensaje(JLabel lbl_mensaje) {
        this.lbl_mensaje = lbl_mensaje;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agendar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_mascotas;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_ver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlbMenuInicio;
    private javax.swing.JLabel lbl_mensaje;
    // End of variables declaration//GEN-END:variables
}
