package Vista;

import Controlador.ControladorAgendarCita;
import Controlador.ControladorDetalleCita;
import Controlador.ControladorMenuInicio;
import Fecha.Fecha;
import Modelo.Componentes.FechaIsNull;
import Modelo.Componentes.SelecFecha;
import Modelo.VO.Cita;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author pesca
 */
public class VistaAgendarCita extends javax.swing.JDialog {

    /**
     * Creates new form Ventana_4
     */
    public VistaAgendarCita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public VistaAgendarCita() {
        super();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_regresar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lb_estetico = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comb_tipo = new javax.swing.JComboBox<>();
        comb_estetico = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combo_mascotas = new javax.swing.JComboBox<>();
        selecFecha = new Modelo.Componentes.SelecFecha();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(200, 228, 228));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(200, 228, 228));

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("The munday free version", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("AGENDAR CITA");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel2.add(jLabel1);

        jPanel4.add(jPanel2);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(200, 228, 228));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_regresar.setBackground(new java.awt.Color(255, 255, 255));
        btn_regresar.setFont(new java.awt.Font("The munday free version", 1, 12)); // NOI18N
        btn_regresar.setForeground(new java.awt.Color(0, 51, 255));
        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        jPanel5.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, 30));

        btn_siguiente.setBackground(new java.awt.Color(255, 255, 255));
        btn_siguiente.setFont(new java.awt.Font("The munday free version", 1, 12)); // NOI18N
        btn_siguiente.setForeground(new java.awt.Color(0, 51, 255));
        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });
        jPanel5.add(btn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 30));

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lb_estetico.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        lb_estetico.setForeground(new java.awt.Color(0, 153, 204));
        lb_estetico.setText("Estetico");
        lb_estetico.setVisible(false);
        lb_estetico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_esteticoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_esteticoMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("TIpo de cita");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("FECHA");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        comb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Revision", "Esterelizacion", "Estetico", "Vacunacion" }));
        comb_tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comb_tipoItemStateChanged(evt);
            }
        });
        comb_tipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comb_tipoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                comb_tipoFocusLost(evt);
            }
        });
        comb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_tipoActionPerformed(evt);
            }
        });

        comb_estetico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baño", "Corte" }));
        comb_estetico.setVisible(false);
        comb_estetico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comb_esteticoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                comb_esteticoFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Selecciona a tu mascota");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(comb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_estetico)
                            .addComponent(comb_estetico, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selecFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(combo_mascotas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(376, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lb_estetico)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comb_estetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(selecFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(combo_mascotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        try {
            // TODO add your handling code here:
            Cita cita = ControladorAgendarCita.crearCita();
            this.setVisible(false);
            ControladorDetalleCita.mostrarVentana();
            ControladorDetalleCita.mostrarDatos(cita);
            new ControladorDetalleCita(cita);
        } catch (FechaIsNull ex) {
            JOptionPane.showMessageDialog(this, "Se debe de selecciionar una fecha");
        }
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ControladorMenuInicio.setVisible(true);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setForeground(Color.PINK);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setForeground(new Color(0, 153, 204));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:{
        jLabel3.setForeground(new Color(0, 153, 204));
    }//GEN-LAST:event_jLabel3MouseExited


    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setForeground(Color.GREEN);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void comb_esteticoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comb_esteticoFocusLost
        // TODO add your handling code here:
        comb_estetico.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_comb_esteticoFocusLost

    private void comb_esteticoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comb_esteticoFocusGained
        // TODO add your handling code here:
        comb_estetico.setBackground(new Color(102, 204, 255));

    }//GEN-LAST:event_comb_esteticoFocusGained

    private void comb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_tipoActionPerformed

    private void comb_tipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comb_tipoFocusLost
        // TODO add your handling code here:
        comb_tipo.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_comb_tipoFocusLost

    private void comb_tipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comb_tipoFocusGained
        // TODO add your handling code here:
        comb_tipo.setBackground(new Color(102, 204, 255));
    }//GEN-LAST:event_comb_tipoFocusGained

    private void comb_tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comb_tipoItemStateChanged
        // TODO add your handling code here:
        ControladorAgendarCita.evento();
    }//GEN-LAST:event_comb_tipoItemStateChanged

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        jLabel5.setForeground(new Color(0, 153, 204));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        jLabel5.setForeground(Color.GREEN);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        jLabel4.setForeground(new Color(0, 153, 204));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        jLabel4.setForeground(Color.GREEN);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void lb_esteticoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_esteticoMouseExited
        // TODO add your handling code here:
        lb_estetico.setForeground(new Color(0, 153, 204));
    }//GEN-LAST:event_lb_esteticoMouseExited

    private void lb_esteticoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_esteticoMouseEntered
        // TODO add your handling code here:
        lb_estetico.setForeground(Color.GREEN);
    }//GEN-LAST:event_lb_esteticoMouseEntered

    public JComboBox<String> getCombo_mascotas() {
        return combo_mascotas;
    }

    public void setCombo_mascotas(JComboBox<String> combo_mascotas) {
        this.combo_mascotas = combo_mascotas;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaAgendarCita dialog = new VistaAgendarCita(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public SelecFecha getSelecFecha() {
        return selecFecha;
    }

    public void setSelecFecha(SelecFecha selecFecha) {
        this.selecFecha = selecFecha;
    }

    public JLabel getLb_estetico() {
        return lb_estetico;
    }

    public void setLb_estetico(JLabel lb_estetico) {
        this.lb_estetico = lb_estetico;
    }

    public JButton getBtn_agendar() {
        return btn_siguiente;
    }

    public void setBtn_agendar(JButton btn_agendar) {
        this.btn_siguiente = btn_agendar;
    }

    public JButton getBtn_regresar() {
        return btn_regresar;
    }

    public void setBtn_regresar(JButton btn_regresar) {
        this.btn_regresar = btn_regresar;
    }

    public JComboBox<String> getComb_estetico() {
        return comb_estetico;
    }

    public void setComb_estetico(JComboBox<String> comb_estetico) {
        this.comb_estetico = comb_estetico;
    }

    public JComboBox<String> getComb_tipo() {
        return comb_tipo;
    }

    public void setComb_tipo(JComboBox<String> comb_tipo) {
        this.comb_tipo = comb_tipo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comb_estetico;
    private javax.swing.JComboBox<String> comb_tipo;
    private javax.swing.JComboBox<String> combo_mascotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lb_estetico;
    private Modelo.Componentes.SelecFecha selecFecha;
    // End of variables declaration//GEN-END:variables
}
