/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Modelo.Componentes;

import Fecha.Fecha;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JSpinner;

/**
 *
 * @author gambo
 */
public class ComponenteFecha extends javax.swing.JPanel {

    /**
     * Creates new form ComponenteFecha
     */
    public ComponenteFecha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sel_fecha = new com.toedter.calendar.JDateChooser();
        combo_horas = new javax.swing.JComboBox<>();

        combo_horas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00" }));
        combo_horas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_horasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sel_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sel_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(combo_horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combo_horasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_horasItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_horasItemStateChanged

    public Fecha getFecha() {
        LocalDate localdate = dateToLocalDate();
        int dia = localdate.getDayOfMonth();
        int mes = localdate.getDayOfMonth();
        int anio = localdate.getYear();
        int hora = getHora();
        Fecha fecha = new Fecha(dia, mes, anio, hora, mes);
        return fecha;
    }

    public LocalDate dateToLocalDate() {
        Date date = sel_fecha.getDate();
        return date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }

    public int getHora() {
        String hora = (String) combo_horas.getSelectedItem();

        int decena = hora.charAt(0) * 10;
        int unidad = hora.charAt(1) * 1;
        return decena + unidad;
    }
    
    public void removeHora(){
        int index = combo_horas.getSelectedIndex();
        combo_horas.remove(index);
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_horas;
    private com.toedter.calendar.JDateChooser sel_fecha;
    // End of variables declaration//GEN-END:variables
}
